### PR TITLE
FEATURE: user can provide origin and resolutions for WMTS Tile Grid

### PR DESCRIPTION
**Pull request by chrudosvorlicek**
This pull request adds possibility to define own origin and resolution for WMTS Tile grid as defined in https://openlayers.org/en/latest/apidoc/module-ol_tilegrid_WMTS-WMTSTileGrid.html

### CODE REVIEW

**Comment by chrudosvorlicek** [comment]
glad to help, thanks for merge

**Comment by chrudosvorlicek** [comment]
Will you make new minor version release from this? It's basically bugfix since openlayers supports it and support for WMTS tile grid in vuelayers is missing it.

**Comment by ghettovoice** [comment]
I can do it within days

**Comment by chrudosvorlicek** [comment]
thanks a lot

**Pull request merged**
