### PR TITLE
bump ol. Test are failing

### PR DESCRIPTION
**Pull request by RemiDesgrange**
First attempt to bump ol to version 6. Test are failing on my laptop.

I did: 

```
npm i
npm run test
```
It first tells me that I missed `babel-polyfill`. 

`ol-tilecache`do not need and update if I read stuff correctly.

### CODE REVIEW

**Comment by ghettovoice** [comment]
Hi @RemiDesgrange ,
thanks for contribution!
Yeh, your are right, firstly the `ol-tilecache` should be upgraded too. 
And I start resolving this part.
Then I come back to here

**Comment by RemiDesgrange** [comment]
:+1: Note that on my machine, I install polyfill, checkout on `master`, npm i again (to have ol5). Test pass. Then checkout my branch, and test pass (e2e too). So *maybe* ol-tilecache doesn't need anything. There are really a few breacking changes in ol6. ol6 is mostly new features ;-)

**Comment by RemiDesgrange** [comment]
@ghettovoice could it be at least merged to master to release a latest tag on npm and then work problems around ?

**Comment by ghettovoice** [comment]
Published on npm under `dev` tag from `ol-next` branch. You can install with `npm i vuelayers@dev`.
I'm working on a full upgrade in the another branch, so `ol-next` is used for very early dev release

**Comment by RemiDesgrange** [comment]
Thanks !!

**Pull request closed without merging**
