### PR TITLE
improve map component defaultInteractionsOptions prop

### PR DESCRIPTION
**Pull request by jemasfox**
Added a defaultInteractionsOptions prop to the map component to be able to pass options into the interactions defaults function when map.vue calls it. 
I mainly needed a way to add the onFocusOnly boolean in so the DragPan and MouseWheelZoom interactions only activate on map focus. I tried many other ways to accomplish this without having to create a set of interactions of my own. I even tried setting the interactions on mounted and created using the defaults function the same way the map component does, but for some reason the map property didn't get set for the interactions and openlayers was logging errors to the console any time I used DragPan.

### CODE REVIEW

**Comment by ghettovoice** [comment]
Thanks for contribution!

**Comment by majdal** [comment]
Hello hello - I'm looking at the Master branch, and it looks like the `defaultInteractionsOptions` prop is no longer there. 

Is there a recommended way set `onFocusOnly` on an interaction?

**Comment by jemasfox** [comment]
> Hello hello - I'm looking at the Master branch, and it looks like the `defaultInteractionsOptions` prop is no longer there.
> 
> Is there a recommended way set `onFocusOnly` on an interaction?

I believe the prop was changed to defaultInteractions. I think the way that was working for me was to set the prop on the vl-map.
Something like `:default-interactions="{ constrainResolution: true, onFocusOnly: true }"`.
I think I also put a click event handler on it's parent div which calls a function that basically just has this
`if (document.activeElement.id !== 'vl-map-map-component') document.getElementById('vl-map-map-component').focus();`
Hope that helps you out.

**Comment by ghettovoice** [comment]
Hi there!
Yes, this prop was renamed some time ago. I'm not sure when..
Anyway it is named as `defaultInteractions` in v0.12 and v0.11

**Comment by majdal** [comment]
Beautiful :) Works as expected.

I'm guessing that this would be very useful to other developers. Maybe we should add it to the docs at [vl-map#properties](https://vuelayers.github.io/#/docs/component/map?id=properties)?

**Pull request merged**
